remote_theme: amitmerchant1990/reverie


# Name of your site (displayed in the header)
name: Reverie Test Site

# Name of the author
author: Elsa Culler

# Short bio or description (displayed in the header)
description: Testing the Reverie theme by Amit Merchant
