remote_theme: brianmaierjr/long-haul


# Name of your site (displayed in the header)
title: Long Haul Test Site

# Name of the author
author: Elsa Culler

# Short bio or description (displayed in the header)
description: Testing the Long Haul theme by Brian Maier Jr.
